forever accesibility script change

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,4 +1,5 @@
 #!/bin/bash
 cd /home/ubuntu || echo "prevent cd fatal error"
 pkill -f bot.js || echo "process not running"
-forever start bot.js || echo "prevent forever fatal error"
+export HOME=/home/ubuntu/ || echo "export failed"
+sudo -u root forever start bot.js || echo "prevent forever fatal error"
